import worldmap from '../public/images/location/worldmap.png';
import unitedStates from '../public/images/countries/unitedStates.png';

export default {
	header: {
		id: 1,
		title: 'Locations',
		description: 'We offer real and unique residential proxies in 170+ locations  around the globe',
		img: worldmap,
	},
	topLocation: [
		{
			id: 41,
			name: 'United States',
			flag: unitedStates,
			ips: 4742389,
			shortname: 'united-states',
			code: 'us',
		},
		{
			id: 42,
			name: 'Canada',
			flag: unitedStates,
			ips: 497982,
			shortname: 'canada',
			code: 'ca',
		},
		{
			id: 43,
			name: 'Ukraine',
			flag: unitedStates,
			ips: 7163,
			shortname: 'ukraine',
			code: 'ua',
		},
		{
			id: 44,
			name: 'United Kingdom',
			flag: unitedStates,
			ips: 1704330,
			code: 'gb',
			shortname: 'united-kingdom',
		},
		{
			id: 45,
			name: 'Germany',
			flag: unitedStates,
			ips: 696238,
			shortname: 'germany',
			code: 'de',
		},
		{
			id: 46,
			name: 'Spain',
			flag: unitedStates,
			ips: 412075,
			shortname: 'spain',
			code: 'es',
		},
		{
			id: 47,
			name: 'Russia',
			flag: unitedStates,
			ips: 1734418,
			shortname: 'russia',
			code: 'ru',
		},
		{
			id: 48,
			name: 'Japan',
			flag: unitedStates,
			ips: 108868,
			shortname: 'japan',
			code: 'jp',
		},
		{
			id: 49,
			name: 'South Korea',
			flag: unitedStates,
			ips: 106831,
			shortname: 'south-korea',
			code: 'kr',
		},
	],
	locations: [
		{
			id: 1,
			name: 'Argentina',
			flag: unitedStates,
			ips: 4742389,
			shortname: 'argentina',
			code: 'ar',
		},
		{
			id: 2,
			name: 'Australia',
			flag: unitedStates,
			ips: 497982,
			shortname: 'australia',
			code: 'au',
		},
		{
			id: 3,
			name: 'Austria',
			flag: unitedStates,
			ips: 7163,
			shortname: 'austria',
			code: 'at',
		},
		{
			id: 4,
			name: 'Bahrain',
			flag: unitedStates,
			ips: 1704330,
			shortname: 'bahrain',
			code: 'bh',
		},
		{
			id: 5,
			name: 'Belarus',
			flag: unitedStates,
			ips: 696238,
			shortname: 'belarus',
			code: 'by',
		},
		{
			id: 6,
			name: 'Brazil',
			flag: unitedStates,
			ips: 412075,
			shortname: 'brazil',
			code: 'br',
		},
		{
			id: 7,
			name: 'Canada',
			flag: unitedStates,
			ips: 1734418,
			shortname: 'canada',
			code: 'ca',
		},
		{
			id: 8,
			name: 'Chile',
			flag: unitedStates,
			ips: 108868,
			shortname: 'chile',
			code: 'cl',
		},
		{
			id: 9,
			name: 'China',
			flag: unitedStates,
			ips: 106831,
			shortname: 'china',
			code: 'cn',
		},
		{
			id: 10,
			name: 'Colombia',
			flag: unitedStates,
			ips: 4742389,
			shortname: 'colombia',
			code: 'co',
		},
		{
			id: 11,
			name: 'Croatia',
			flag: unitedStates,
			ips: 497982,
			shortname: 'croatia',
			code: 'hr',
		},
		{
			id: 12,
			name: 'Czech Republic',
			flag: unitedStates,
			ips: 7163,
			shortname: 'czech-republic',
			code: 'cz',
		},
		{
			id: 13,
			name: 'Denmark',
			flag: unitedStates,
			ips: 1704330,
			shortname: 'denmark',
			code: 'dk',
		},
		{
			id: 14,
			name: 'Ecuador',
			flag: unitedStates,
			ips: 696238,
			shortname: 'ecuador',
			code: 'ec',
		},
		{
			id: 15,
			name: 'Estonia',
			flag: unitedStates,
			ips: 412075,
			shortname: 'estonia',
			code: 'ee',
		},
		{
			id: 16,
			name: 'Finland',
			flag: unitedStates,
			ips: 1734418,
			shortname: 'finland',
			code: 'fi',
		},
		{
			id: 17,
			name: 'France',
			flag: unitedStates,
			ips: 108868,
			shortname: 'france',
			code: 'fr',
		},
		{
			id: 18,
			name: 'Germany',
			flag: unitedStates,
			ips: 106831,
			shortname: 'germany',
			code: 'de',
		},
		{
			id: 19,
			name: 'Greece',
			flag: unitedStates,
			ips: 4742389,
			shortname: 'greece',
			code: 'gr',
		},
		{
			id: 20,
			name: 'Hong Kong',
			flag: unitedStates,
			ips: 497982,
			shortname: 'hong-kong',
			code: 'hk',
		},
		{
			id: 21,
			name: 'Hungary',
			flag: unitedStates,
			ips: 7163,
			shortname: 'hungary',
			code: 'hu',
		},
		{
			id: 22,
			name: 'Iceland',
			flag: unitedStates,
			ips: 1704330,
			shortname: 'iceland',
			code: 'is',
		},
		{
			id: 23,
			name: 'India',
			flag: unitedStates,
			ips: 696238,
			shortname: 'india',
			code: 'in',
		},
		{
			id: 24,
			name: 'Indonesia',
			flag: unitedStates,
			ips: 412075,
			shortname: 'indonesia',
			code: 'id',
		},
		{
			id: 25,
			name: 'Ireland',
			flag: unitedStates,
			ips: 1734418,
			shortname: 'ireland',
			code: 'ie',
		},
		{
			id: 26,
			name: 'Israel',
			flag: unitedStates,
			ips: 108868,
			shortname: 'israel',
			code: 'il',
		},
		{
			id: 27,
			name: 'Italy',
			flag: unitedStates,
			ips: 106831,
			shortname: 'italy',
			code: 'it',
		},
		{
			id: 28,
			name: 'Japan',
			flag: unitedStates,
			ips: 4742389,
			shortname: 'japan',
			code: 'jp',
		},
		{
			id: 29,
			name: 'Jordan',
			flag: unitedStates,
			ips: 497982,
			shortname: 'jordan',
			code: 'jo',
		},
		{
			id: 30,
			name: 'Kazachstan',
			flag: unitedStates,
			ips: 7163,
			shortname: 'kazachstan',
			code: 'kz',
		},
		{
			id: 31,
			name: 'Kuwait',
			flag: unitedStates,
			ips: 1704330,
			shortname: 'kuwait',
			code: 'kw',
		},
		{
			id: 32,
			name: 'Malaysia',
			flag: unitedStates,
			ips: 696238,
			shortname: 'malaysia',
			code: 'my',
		},
		{
			id: 33,
			name: 'Mexico',
			flag: unitedStates,
			ips: 412075,
			shortname: 'mexico',
			code: 'mx',
		},
		{
			id: 34,
			name: 'Netherlands',
			flag: unitedStates,
			ips: 1734418,
			shortname: 'netherlands',
			code: 'nl',
		},
		{
			id: 35,
			name: 'New Zealand',
			flag: unitedStates,
			ips: 108868,
			shortname: 'new-zealand',
			code: 'nz',
		},
		{
			id: 36,
			name: 'Norway',
			flag: unitedStates,
			ips: 1704330,
			shortname: 'norway',
			code: 'no',
		},
		{
			id: 37,
			name: 'Oman',
			flag: unitedStates,
			ips: 696238,
			shortname: 'oman',
			code: 'om',
		},
		{
			id: 38,
			name: 'Peru',
			flag: unitedStates,
			ips: 412075,
			shortname: 'peru',
			code: 'pe',
		},
		{
			id: 39,
			name: 'Philippines',
			flag: unitedStates,
			ips: 1734418,
			shortname: 'philippines',
			code: 'ph',
		},
		{
			id: 40,
			name: 'Poland',
			flag: unitedStates,
			ips: 108868,
			shortname: 'poland',
			code: 'pl',
		},
	],

	allLocation: [
		{
			id: 1,
			name: 'Argentina',
			flag: unitedStates,
			ips: 4742389,
			shortname: 'argentina',
			code: 'ar',
		},
		{
			id: 2,
			name: 'Australia',
			flag: unitedStates,
			ips: 497982,
			shortname: 'australia',
			code: 'au',
		},
		{
			id: 3,
			name: 'Austria',
			flag: unitedStates,
			ips: 7163,
			shortname: 'austria',
			code: 'at',
		},
		{
			id: 4,
			name: 'Bahrain',
			flag: unitedStates,
			ips: 1704330,
			shortname: 'bahrain',
			code: 'bh',
		},
		{
			id: 5,
			name: 'Belarus',
			flag: unitedStates,
			ips: 696238,
			shortname: 'belarus',
			code: 'by',
		},
		{
			id: 6,
			name: 'Brazil',
			flag: unitedStates,
			ips: 412075,
			shortname: 'brazil',
			code: 'br',
		},
		{
			id: 7,
			name: 'Canada',
			flag: unitedStates,
			ips: 1734418,
			shortname: 'canada',
			code: 'ca',
		},
		{
			id: 8,
			name: 'Chile',
			flag: unitedStates,
			ips: 108868,
			shortname: 'chile',
			code: 'cl',
		},
		{
			id: 9,
			name: 'China',
			flag: unitedStates,
			ips: 106831,
			shortname: 'china',
			code: 'cn',
		},
		{
			id: 10,
			name: 'Colombia',
			flag: unitedStates,
			ips: 4742389,
			shortname: 'colombia',
			code: 'co',
		},
		{
			id: 11,
			name: 'Croatia',
			flag: unitedStates,
			ips: 497982,
			shortname: 'croatia',
			code: 'hr',
		},
		{
			id: 12,
			name: 'Czech Republic',
			flag: unitedStates,
			ips: 7163,
			shortname: 'czech-republic',
			code: 'cz',
		},
		{
			id: 13,
			name: 'Denmark',
			flag: unitedStates,
			ips: 1704330,
			shortname: 'denmark',
			code: 'dk',
		},
		{
			id: 14,
			name: 'Ecuador',
			flag: unitedStates,
			ips: 696238,
			shortname: 'ecuador',
			code: 'ec',
		},
		{
			id: 15,
			name: 'Estonia',
			flag: unitedStates,
			ips: 412075,
			shortname: 'estonia',
			code: 'ee',
		},
		{
			id: 16,
			name: 'Finland',
			flag: unitedStates,
			ips: 1734418,
			shortname: 'finland',
			code: 'fi',
		},
		{
			id: 17,
			name: 'France',
			flag: unitedStates,
			ips: 108868,
			shortname: 'france',
			code: 'fr',
		},
		{
			id: 18,
			name: 'Germany',
			flag: unitedStates,
			ips: 106831,
			shortname: 'germany',
			code: 'de',
		},
		{
			id: 19,
			name: 'Greece',
			flag: unitedStates,
			ips: 4742389,
			shortname: 'greece',
			code: 'gr',
		},
		{
			id: 20,
			name: 'Hong Kong',
			flag: unitedStates,
			ips: 497982,
			shortname: 'hong-kong',
			code: 'hk',
		},
		{
			id: 21,
			name: 'Hungary',
			flag: unitedStates,
			ips: 7163,
			shortname: 'hungary',
			code: 'hu',
		},
		{
			id: 22,
			name: 'Iceland',
			flag: unitedStates,
			ips: 1704330,
			shortname: 'iceland',
			code: 'is',
		},
		{
			id: 23,
			name: 'India',
			flag: unitedStates,
			ips: 696238,
			shortname: 'india',
			code: 'in',
		},
		{
			id: 24,
			name: 'Indonesia',
			flag: unitedStates,
			ips: 412075,
			shortname: 'indonesia',
			code: 'id',
		},
		{
			id: 25,
			name: 'Ireland',
			flag: unitedStates,
			ips: 1734418,
			shortname: 'ireland',
			code: 'ie',
		},
		{
			id: 26,
			name: 'Israel',
			flag: unitedStates,
			ips: 108868,
			shortname: 'israel',
			code: 'il',
		},
		{
			id: 27,
			name: 'Italy',
			flag: unitedStates,
			ips: 106831,
			shortname: 'italy',
			code: 'it',
		},
		{
			id: 28,
			name: 'Japan',
			flag: unitedStates,
			ips: 4742389,
			shortname: 'japan',
			code: 'jp',
		},
		{
			id: 29,
			name: 'Jordan',
			flag: unitedStates,
			ips: 497982,
			shortname: 'jordan',
			code: 'jo',
		},
		{
			id: 30,
			name: 'Kazachstan',
			flag: unitedStates,
			ips: 7163,
			shortname: 'kazachstan',
			code: 'kz',
		},
		{
			id: 31,
			name: 'Kuwait',
			flag: unitedStates,
			ips: 1704330,
			shortname: 'kuwait',
			code: 'kw',
		},
		{
			id: 32,
			name: 'Malaysia',
			flag: unitedStates,
			ips: 696238,
			shortname: 'malaysia',
			code: 'my',
		},
		{
			id: 33,
			name: 'Mexico',
			flag: unitedStates,
			ips: 412075,
			shortname: 'mexico',
			code: 'mx',
		},
		{
			id: 34,
			name: 'Netherlands',
			flag: unitedStates,
			ips: 1734418,
			shortname: 'netherlands',
			code: 'nl',
		},
		{
			id: 35,
			name: 'New Zealand',
			flag: unitedStates,
			ips: 108868,
			shortname: 'new-zealand',
			code: 'nz',
		},
		{
			id: 36,
			name: 'Norway',
			flag: unitedStates,
			ips: 1704330,
			shortname: 'norway',
			code: 'no',
		},
		{
			id: 37,
			name: 'Oman',
			flag: unitedStates,
			ips: 696238,
			shortname: 'oman',
			code: 'om',
		},
		{
			id: 38,
			name: 'Peru',
			flag: unitedStates,
			ips: 412075,
			shortname: 'peru',
			code: 'pe',
		},
		{
			id: 39,
			name: 'Philippines',
			flag: unitedStates,
			ips: 1734418,
			shortname: 'philippines',
			code: 'ph',
		},
		{
			id: 40,
			name: 'Poland',
			flag: unitedStates,
			ips: 108868,
			shortname: 'poland',
			code: 'pl',
		},
		{
			id: 41,
			name: 'United States',
			flag: unitedStates,
			ips: 4742389,
			shortname: 'united-states',
			code: 'us',
		},
		{
			id: 42,
			name: 'Ukraine',
			flag: unitedStates,
			ips: 7163,
			shortname: 'ukraine',
			code: 'ua',
		},
		{
			id: 43,
			name: 'United Kingdom',
			flag: unitedStates,
			ips: 1704330,
			shortname: 'united-kingdom',
			code: 'gb',
		},
		{
			id: 44,
			name: 'Spain',
			flag: unitedStates,
			ips: 412075,
			shortname: 'spain',
			code: 'es',
		},
		{
			id: 45,
			name: 'Russia',
			flag: unitedStates,
			ips: 1734418,
			shortname: 'russia',
			code: 'ru',
		},
		{
			id: 46,
			name: 'South Korea',
			flag: unitedStates,
			ips: 106831,
			shortname: 'south-korea',
			code: 'kr',
		},
	],

	countries: [
		{
			id: 1,
			name: 'Afghanistan',
			ips: 106831,
			shortname: 'afghanistan',
			metaTitle: '🇦🇫 Afghanistan Proxy Server [2022 Afghanistran IP Address]',
			code: 'af',
		},
		{
			id: 2,
			name: 'Albania',
			ips: 106831,
			shortname: 'albania',
			metaTitle: '🇦🇱 Albania Proxy Server List [2022 Albanian Proxies]',
			code: 'al',
		},
		{
			id: 3,
			name: 'Algeria',
			ips: 106831,
			shortname: 'algeria',
			metaTitle: '🇩🇿 Algeria Proxy Server [2022 Algerian Proxies]',
			code: 'dz',
		},
		// {
		// 	id: 4,
		// 	name: 'American Samoa',
		// 	ips: 106831,
		// 	shortname: 'american-samoa',
		// 	code: 'as',
		// },
		{
			id: 5,
			name: 'Andorra',
			ips: 106831,
			shortname: 'andorra',
			metaTitle: '🇦🇩 Andorra Proxy Server [2022 Andorra Proxies]',
			code: 'ad',
		},
		{
			id: 6,
			name: 'Angola',
			ips: 106831,
			shortname: 'angola',
			metaTitle: '🇦🇴 Angola Proxy Server [2022 Angolian Proxies]',
			code: 'ao',
		},
		// {
		// 	id: 7,
		// 	name: 'Anguilla',
		// 	ips: 106831,
		// 	shortname: 'anguilla',
		// 	code: 'ai',
		// },
		// {
		// 	id: 8,
		// 	name: 'Antarctica',
		// 	ips: 106831,
		// 	shortname: 'antarctica',
		// 	code: 'aq',
		// },
		{
			id: 9,
			name: 'Antigua and Barbuda',
			ips: 106831,
			shortname: 'antigua-and-barbuda',
			metaTitle: '🇦🇬 Antigua and Barbuda Proxy [2022 AB Proxies]',
			code: 'ar',
		},
		{
			id: 10,
			name: 'Argentina',
			ips: 106831,
			shortname: 'argentina',
			metaTitle: '',
			code: 'ar',
		},
		{
			id: 11,
			name: 'Armenia',
			ips: 106831,
			shortname: 'armenia',
			metaTitle: '🇦🇲 Armenia Proxy Server [2022 Armenian IP Address]',
			code: 'am',
		},
		// {
		// 	id: 12,
		// 	name: 'Aruba',
		// 	ips: 106831,
		// 	shortname: '1ruba',
		// 	code: 'aw',
		// },
		{
			id: 13,
			name: 'Australia',
			ips: 106831,
			shortname: 'australia',
			metaTitle: '🇦🇺 Australia Proxy Server [2022 Proxy Australia]',
			code: 'au',
		},
		{
			id: 14,
			name: 'Austria',
			ips: 106831,
			shortname: 'austria',
			metaTitle: '',
			code: 'at',
		},
		{
			id: 15,
			name: 'Azerbaijan',
			ips: 106831,
			shortname: 'azerbaijan',
			metaTitle: '🇦🇿 Azerbaijan Proxy [Azerbaijan Proxy Server]',
			code: 'az',
		},
		{
			id: 16,
			name: 'Bahamas',
			ips: 106831,
			shortname: 'bahamas',
			metaTitle: '🇧🇸 Bahamas Proxy Server [2022 Bahamas Business Proxies]',
			code: 'bs',
		},
		{
			id: 17,
			name: 'Bahrain',
			ips: 106831,
			shortname: 'bahrain',
			metaTitle: '🇧🇭 Bahrain Proxies [Bahrain Proxy List 2022]',
			code: 'bh',
		},
		{
			id: 18,
			name: 'Bangladesh',
			ips: 106831,
			shortname: 'bangladesh',
			metaTitle: '🇧🇩 Bangladesh Proxy Server [Bangladesh Proxy 2022]',
			code: 'bd',
		},
		{
			id: 19,
			name: 'Barbados',
			ips: 106831,
			shortname: 'barbados',
			metaTitle: '🇧🇧 Proxy Barbados 2022 [Barbados IP Address]',
			code: 'bb',
		},
		{
			id: 20,
			name: 'Belarus',
			ips: 106831,
			shortname: 'belarus',
			metaTitle: '🇧🇾 Belarus Proxy Server [ Premium Belarus Proxy List]',
			code: 'by',
		},
		{
			id: 21,
			name: 'Belgium',
			ips: 106831,
			shortname: 'belgium',
			metaTitle: '🇧🇪 Proxy Belgium [2022 Belgium Proxy]',
			code: 'be',
		},
		{
			id: 22,
			name: 'Belize',
			ips: 106831,
			shortname: 'belize',
			metaTitle: '🇧🇿 Belize Proxy Server [Premium Belize Proxies]',
			code: 'bz',
		},
		{
			id: 23,
			name: 'Benin',
			ips: 106831,
			shortname: 'benin',
			metaTitle: '🇧🇯 Benin Proxy Server [Benin Proxy List]',
			code: 'bj',
		},
		// {
		// 	id: 24,
		// 	name: 'Bermuda',
		// 	ips: 106831,
		// 	shortname: 'bermuda',
		// 	code: 'bm',
		// },
		{
			id: 25,
			name: 'Bhutan',
			ips: 106831,
			shortname: 'bhutan',
			metaTitle: '🇧🇹 Bhuta Proxy List [Bhutan IP Address]',
			code: 'bt',
		},
		{
			id: 26,
			name: 'Bolivia',
			ips: 106831,
			shortname: 'bolivia',
			metaTitle: '🇧🇴 Bolivia Proxy Server [Bolivian Proxies]',
			code: 'bo',
		},
		{
			id: 27,
			name: 'Bosnia and Herzegovina',
			ips: 106831,
			shortname: 'bosnia-and-herzegovina',
			metaTitle: '🇧🇦 Bosnia and Herzegovina Proxy Server [Bosnia IP]',
			code: 'ba',
		},
		{
			id: 28,
			name: 'Botswana',
			ips: 106831,
			shortname: 'botswana',
			metaTitle: '🇧🇼 Bostwana Proxy Server 2022 [Bostwana Proxies]',
			code: 'bw',
		},
		{
			id: 29,
			name: 'Brazil',
			ips: 106831,
			shortname: 'brazil',
			metaTitle: '🇧🇷  Proxy Brazil [Brazilian IP Address]',
			code: 'br',
		},
		// {
		// 	id: 30,
		// 	name: 'British Indian Ocean Territory',
		// 	ips: 106831,
		// 	shortname: 'british-indian-ocean-territory',
		// 	code: 'io',
		// },
		// {
		// 	id: 31,
		// 	name: 'British Virgin Islands',
		// 	ips: 106831,
		// 	shortname: 'britis-virgin-islands',
		// 	code: 'vg',
		// },
		{
			id: 32,
			name: 'Brunei',
			ips: 106831,
			shortname: 'brunei',
			metaTitle: '🇧🇳 Brunei Darussalam Proxy Server  [Brunei IP]',
			code: 'bn',
		},
		{
			id: 33,
			name: 'Bulgaria',
			ips: 106831,
			shortname: 'bulgaria',
			metaTitle: '🇧🇬 Bulgarian Proxy Server [2022 Bulgaria Proxy]',
			code: 'bg',
		},
		{
			id: 34,
			name: 'Burkina Faso',
			ips: 106831,
			shortname: 'burkina-faso',
			metaTitle: '🇧🇫 Burkina Faso Proxy Server [Burkina IP]',
			code: 'bf',
		},
		{
			id: 35,
			name: 'Burundi',
			ips: 106831,
			shortname: 'burundi',
			metaTitle: '🇧🇮 Burundi Proxy Server [Burundi IP Address]',
			code: 'bi',
		},
		{
			id: 36,
			name: 'Cambodia',
			ips: 106831,
			shortname: 'cambodia',
			metaTitle: '🇰🇭 Cambodia Proxy Server [Cambodia Proxies]',
			code: 'kh',
		},
		{
			id: 37,
			name: 'Cameroon',
			ips: 106831,
			shortname: 'cameroon',
			metaTitle: '🇨🇲 Cameroon Proxy Server [2022 Cameroon Proxies]',
			code: 'cm',
		},
		{
			id: 38,
			name: 'Canada',
			ips: 106831,
			shortname: 'canada',
			metaTitle: '🇨🇦 Canada Proxy Servers [Canada IP Address]',
			code: 'ca',
		},
		{
			id: 39,
			name: 'Cape Verde',
			ips: 106831,
			shortname: 'cape-verde',
			metaTitle: '🇨🇻 Cape Verde Proxies [2022 Cape Verde IP]',
			code: 'cv',
		},
		// {
		// 	id: 40,
		// 	name: 'Cayman Islands',
		// 	ips: 106831,
		// 	shortname: 'cayman-islands',
		// 	code: 'ky',
		// },
		{
			id: 41,
			name: 'Central African Republic',
			ips: 106831,
			shortname: 'central-african-republic',
			metaTitle: '🔥 Central Africa Proxy [African IP]',
			code: 'cf',
		},
		{
			id: 42,
			name: 'Chad',
			ips: 106831,
			shortname: 'chad',
			metaTitle: '🇹🇩 Chad Proxy Servers [2022 Chad IP List]',
			code: 'td',
		},
		{
			id: 43,
			name: 'Chile',
			ips: 106831,
			shortname: 'chile',
			metaTitle: '🇨🇱 Chile Proxy Server  [2022 Proxy Chile]',
			code: 'cl',
		},
		{
			id: 44,
			name: 'China',
			ips: 106831,
			shortname: 'china',
			metaTitle: '🇨🇳 China Proxy Server  [2022 CN Proxy]',
			code: 'cn',
		},
		// {
		// 	id: 45,
		// 	name: 'Christmas Island',
		// 	ips: 106831,
		// 	shortname: 'christmas-island',
		// 	code: 'cx',
		// },
		// {
		// 	id: 46,
		// 	name: 'Cocos Islands',
		// 	ips: 106831,
		// 	shortname: 'cocos-islands',
		// 	code: 'cc',
		// },
		{
			id: 47,
			name: 'Colombia',
			ips: 106831,
			shortname: 'colombia',
			metaTitle: '🇨🇴 Colombia Proxy Server  [2022 Proxy Columbia]',
			code: 'co',
		},
		{
			id: 48,
			name: 'Comoros',
			ips: 106831,
			shortname: 'comoros',
			metaTitle: '🇰🇲 Comoros Proxy Server  [2022 Comoros IP]',
			code: 'km',
		},
		// {
		// 	id: 49,
		// 	name: 'Cook Islands',
		// 	ips: 106831,
		// 	shortname: 'cook-islands',
		// 	code: 'ck',
		// },
		{
			id: 50,
			name: 'Costa Rica',
			ips: 106831,
			shortname: 'costa-rica',
			metaTitle: '🇨🇷 Costa Rica Proxy Server List  [Costa Rica IP]',
			code: 'cr',
		},
		{
			id: 51,
			name: 'Croatia',
			ips: 106831,
			shortname: 'croatia',
			metaTitle: '🇭🇷 Croatia Proxy Server [2022 Croatia IP Address]',
			code: 'hr',
		},
		{
			id: 52,
			name: 'Cuba',
			ips: 106831,
			shortname: 'cuba',
			metaTitle: '🇨🇺 Cuba Proxy Server  [Cuba Proxies]',
			code: 'cu',
		},
		// {
		// 	id: 53,
		// 	name: 'Curacao',
		// 	ips: 106831,
		// 	shortname: 'curacao',
		// 	code: 'cw',
		// },
		{
			id: 54,
			name: 'Cyprus',
			ips: 106831,
			shortname: 'cyprus',
			metaTitle: '🇨🇾 Cyprus Proxy Server  [2022 Cyprus IP]',
			code: 'cy',
		},
		{
			id: 55,
			name: 'Czech Republic',
			ips: 106831,
			shortname: 'czech-republic',
			metaTitle: '🇨🇿 Czech Proxy Server [2022 Czech Republic Proxy]',
			code: 'cz',
		},
		{
			id: 56,
			name: 'Democratic Republic of the Congo',
			ips: 106831,
			shortname: 'democratic-republic-of-the-congo',
			metaTitle: '🇨🇩 Congo Proxy Server [Democratic Republic Proxies]',
			code: 'cd',
		},
		{
			id: 57,
			name: 'Denmark',
			ips: 106831,
			shortname: 'denmark',
			metaTitle: '🇩🇰 Denmark Proxy Server [2022 Denmark Proxies]',
			code: 'dk',
		},
		{
			id: 58,
			name: 'Djibouti',
			ips: 106831,
			shortname: 'djibouti',
			metaTitle: '🇩🇯 Djibouti Proxy [2022 Djibouti Proxy List]',
			code: 'dj',
		},
		{
			id: 59,
			name: 'Dominica',
			ips: 106831,
			shortname: 'dominica',
			metaTitle: '🇩🇲 Dominica Proxy List [Dominica Proxy IP]',
			code: 'dm',
		},
		{
			id: 60,
			name: 'Dominican Republic',
			ips: 106831,
			shortname: 'dominican-republic',
			metaTitle: '🇩🇴 Dominican Republic Proxy Servers [2022 DR Proxies]',
			code: 'do',
		},
		{
			id: 61,
			name: 'East Timor',
			ips: 106831,
			shortname: 'east-timor',
			metaTitle: '🔥 East Timor Proxy Servers [East Timor Proxies]',
			code: 'tl',
		},
		{
			id: 62,
			name: 'Ecuador',
			ips: 106831,
			shortname: 'ecuador',
			metaTitle: '🇪🇨 Ecuador Proxy Server List [Ecuador Proxies]',
			code: 'ec',
		},
		{
			id: 63,
			name: 'Egypt',
			ips: 106831,
			shortname: 'egypt',
			metaTitle: '🇪🇬 Egypt Proxy Server List [2022 Proxy Egypt]',
			code: 'eg',
		},
		{
			id: 64,
			name: 'El Salvador',
			ips: 106831,
			shortname: 'el-salvador',
			metaTitle: '🇸🇻 El Salvador Proxy Server List [2022 Proxy El Salvador]',
			code: 'sv',
		},
		{
			id: 65,
			name: 'Equatorial Guinea',
			ips: 106831,
			shortname: 'equatorial-guinea',
			metaTitle: '🇬🇶 Equatorial Guinea Proxy Server  [2022 Guinea Proxies]',
			code: 'gq',
		},
		{
			id: 66,
			name: 'Eritrea',
			ips: 106831,
			shortname: 'eritrea',
			metaTitle: '🇪🇷 Eritrea Proxies  [2022 Eritrea Proxy Server List]',
			code: 'er',
		},
		{
			id: 67,
			name: 'Estonia',
			ips: 106831,
			shortname: 'estonia',
			metaTitle: '🇪🇪 Estonia Proxy Server [2022 Estonia Proxy List]',
			code: 'ee',
		},
		{
			id: 68,
			name: 'Ethiopia',
			ips: 106831,
			shortname: 'ethiopia',
			metaTitle: '🇪🇹 Ethiopia Proxy Server [2022 Ethiopia Proxy List]',
			code: 'et',
		},
		// {
		// 	id: 69,
		// 	name: 'Falkland Islands',
		// 	ips: 106831,
		// 	shortname: 'falkland-islands',
		// 	code: 'fk',
		// },
		// {
		// 	id: 70,
		// 	name: 'Faroe Islands',
		// 	ips: 106831,
		// 	shortname: 'faroe-islands',
		// 	code: 'fo',
		// },
		{
			id: 71,
			name: 'Fiji',
			ips: 106831,
			shortname: 'fiji',
			metaTitle: '🇫🇯 Fiji Proxy Server [Fiji Island Proxy List]',
			code: 'fj',
		},
		{
			id: 72,
			name: 'Finland',
			ips: 106831,
			shortname: 'finland',
			metaTitle: '🇫🇮 Finland Proxy Server [2022 Finland Proxies]',
			code: 'fi',
		},
		{
			id: 73,
			name: 'France',
			ips: 106831,
			shortname: 'france',
			metaTitle: '🇫🇷 France Proxy Server [2022 French Proxies]',
			code: 'fr',
		},
		// {
		// 	id: 74,
		// 	name: 'French Polynesia',
		// 	ips: 106831,
		// 	shortname: 'french-polynesia',
		// 	code: 'pf',
		// },
		{
			id: 75,
			name: 'Gabon',
			ips: 106831,
			shortname: 'gabon',
			metaTitle: '🇬🇦 Gabon Proxy Server [2022 Gabon Proxies]',
			code: 'ga',
		},
		{
			id: 76,
			name: 'Gambia',
			ips: 106831,
			shortname: 'gambia',
			metaTitle: '🇬🇲 Gambia Proxy Server [2022 Gambia Proxies]',
			code: 'gm',
		},
		{
			id: 77,
			name: 'Georgia',
			ips: 106831,
			shortname: 'georgia',
			metaTitle: '🇬🇪 Georgia Proxy Server [2022 Georgia Proxies]',
			code: 'ge',
		},
		{
			id: 78,
			name: 'Germany',
			ips: 106831,
			shortname: 'germany',
			metaTitle: '🇩🇪 Germany Proxy Server [2022 German Proxy]',
			code: 'de',
		},
		{
			id: 79,
			name: 'Ghana',
			ips: 106831,
			shortname: 'ghana',
			metaTitle: '🇬🇭 Ghana IP Address [2022 Ghana Proxy List]',
			code: 'gh',
		},
		// {
		// 	id: 80,
		// 	name: 'Gibraltar',
		// 	ips: 106831,
		// 	shortname: 'gibraltar',
		// 	code: 'gi',
		// },
		{
			id: 81,
			name: 'Greece',
			ips: 106831,
			shortname: 'greece',
			metaTitle: '🇬🇷 Greek Proxy Server [2022 Greece Proxies]',
			code: 'gr',
		},
		// {
		// 	id: 82,
		// 	name: 'Greenland',
		// 	ips: 106831,
		// 	shortname: 'greenland',
		// 	code: 'gl',
		// },
		{
			id: 83,
			name: 'Grenada',
			ips: 106831,
			shortname: 'grenada',
			metaTitle: '🇬🇩 Grenada Proxy List [2022 Grenada Proxies]',
			code: 'gd',
		},
		// {
		// 	id: 84,
		// 	name: 'Guam',
		// 	ips: 106831,
		// 	shortname: 'guam',
		// 	code: 'gu',
		// },
		{
			id: 85,
			name: 'Guatemala',
			ips: 106831,
			shortname: 'guatemala',
			metaTitle: '🇬🇹 Guatemala Proxy Server [2022 Proxy Guatemala]',
			code: 'gt',
		},
		// {
		// 	id: 86,
		// 	name: 'Guernsey',
		// 	ips: 106831,
		// 	shortname: 'guernsey',
		// 	code: 'gg',
		// },
		{
			id: 87,
			name: 'Guinea',
			ips: 106831,
			shortname: 'guinea',
			metaTitle: '🇬🇳 Guinea Proxy List [2022 Guinea Proxies]',
			code: 'gn',
		},
		{
			id: 88,
			name: 'Guinea-Bissau',
			ips: 106831,
			shortname: 'guinea-bissau',
			metaTitle: '🇬🇼 Guinea-Bissau Proxy Server [2022 GB Proxies]',
			code: 'gw',
		},
		{
			id: 89,
			name: 'Guyana',
			ips: 106831,
			shortname: 'guyana',
			metaTitle: '🇬🇾 Guyana Proxy Server [2022 Guyana Proxies]',
			code: 'gy',
		},
		{
			id: 90,
			name: 'Haiti',
			ips: 106831,
			shortname: 'haiti',
			metaTitle: '🇭🇹 Haiti Proxy List [2022 Haiti Proxies]',
			code: 'ht',
		},
		{
			id: 91,
			name: 'Honduras',
			ips: 106831,
			shortname: 'honduras',
			metaTitle: '🇭🇳 Honduras Proxy Server [2022 Honduras Proxies]',
			code: 'hn',
		},
		{
			id: 92,
			name: 'Hong Kong',
			ips: 106831,
			shortname: 'hong-kong',
			metaTitle: '🇭🇰 Hong Kong Proxy List [2022 Proxy Hong Kong]',
			code: 'hk',
		},
		{
			id: 93,
			name: 'Hungary',
			ips: 106831,
			shortname: 'hungary',
			metaTitle: '🇭🇺 Hungary Proxy Server [2022 Hungary Proxy]',
			code: 'hu',
		},
		{
			id: 94,
			name: 'Iceland',
			ips: 106831,
			shortname: 'iceland',
			metaTitle: '🇮🇸 Iceland Proxy Server [2022 Iceland Proxies]',
			code: 'is',
		},
		{
			id: 95,
			name: 'India',
			ips: 106831,
			shortname: 'india',
			metaTitle: '🇮🇳 Indian Proxy Server [2022 Indian Proxy Server]',
			code: 'in',
		},
		{
			id: 96,
			name: 'Indonesia',
			ips: 106831,
			shortname: 'indonesia',
			metaTitle: '🇮🇩 Indonesia Proxy Server [2022 Indonesian Proxy]',
			code: 'id',
		},
		{
			id: 97,
			name: 'Iran',
			ips: 106831,
			shortname: 'iran',
			metaTitle: '🇮🇷 Iran Proxy Server [2022 Iran Proxies]',
			code: 'ir',
		},
		{
			id: 98,
			name: 'Iraq',
			ips: 106831,
			shortname: 'iraq',
			metaTitle: '🇮🇶 Iraq Proxy Server [2022 Iraq IP Address]',
			code: 'iq',
		},
		{
			id: 99,
			name: 'Ireland',
			ips: 106831,
			shortname: 'ireland',
			metaTitle: '🇮🇪 Ireland Proxy List [2022 Ireland Proxy Server',
			code: 'ie',
		},
		// {
		// 	id: 100,
		// 	name: 'Isle of Man',
		// 	ips: 106831,
		// 	shortname: 'isle-of-man',
		// 	code: 'im',
		// },
		{
			id: 101,
			name: 'Israel',
			ips: 106831,
			shortname: 'israel',
			metaTitle: '🇮🇱 Israel Proxy List [2022 Proxy Israel]',
			code: 'il',
		},
		{
			id: 102,
			name: 'Italy',
			ips: 106831,
			shortname: 'italy',
			metaTitle: '🇮🇹 Italian Proxy Server [2022 Proxy Italy]',
			code: 'it',
		},
		{
			id: 103,
			name: 'Ivory Coast',
			ips: 106831,
			shortname: 'ivory-coast',
			metaTitle: '🇨🇮 Ivory Coast Proxy List [2022 Ivory Coast Proxies]',
			code: 'ci',
		},
		{
			id: 104,
			name: 'Jamaica',
			ips: 106831,
			shortname: 'jamaica',
			metaTitle: '🇯🇲 Proxy Server Jamaica [2022 Jamaica Proxy]',
			code: 'jm',
		},
		{
			id: 105,
			name: 'Japan',
			ips: 106831,
			shortname: 'japan',
			metaTitle: '🇯🇵 Japan Proxy Server [2022 Japanese Proxies]',
			code: 'jp',
		},
		// {
		// 	id: 106,
		// 	name: 'Jersey',
		// 	ips: 106831,
		// 	shortname: 'jersey',
		// 	code: 'je',
		// },
		{
			id: 107,
			name: 'Jordan',
			ips: 106831,
			shortname: 'jordan',
			metaTitle: '🇯🇴 Jordan Proxy Server [2022 Proxies Jordan]',
			code: 'jo',
		},
		{
			id: 108,
			name: 'Kazakhstan',
			ips: 106831,
			shortname: 'kazakhstan',
			metaTitle: '🇰🇿 Kazakhstan Proxy List [2022 Proxy Server Kazakhstan]',
			code: 'kz',
		},
		{
			id: 109,
			name: 'Kenya',
			ips: 106831,
			shortname: 'kenya',
			metaTitle: '🇰🇪 Kenya Proxy Server [2022 Kenya Proxies]',
			code: 'ke',
		},
		{
			id: 110,
			name: 'Kiribati',
			ips: 106831,
			shortname: 'kiribati',
			metaTitle: '🇰🇮 Kiribati Proxy List [2022 Kiribati Proxies]',
			code: 'ki',
		},
		{
			id: 111,
			name: 'Kosovo',
			ips: 106831,
			shortname: 'kosovo',
			metaTitle: '🇽🇰 Kosovo Proxy Server [2022 Kosovo Proxy YouTube]',
			code: 'xk',
		},
		{
			id: 112,
			name: 'Kuwait',
			ips: 106831,
			shortname: 'kuwait',
			metaTitle: '🇰🇼 Kuwait Proxy List [2022 Web Proxy Kuwait]',
			code: 'kw',
		},
		{
			id: 113,
			name: 'Kyrgyzstan',
			ips: 106831,
			shortname: 'kyrgyzstan',
			metaTitle: '🇰🇬 Kyrgyzstan Proxy Server [2022 Kyrgyzstan Proxies]',
			code: 'kg',
		},
		{
			id: 114,
			name: 'Laos',
			ips: 106831,
			shortname: 'laos',
			metaTitle: '🇱🇦 Laos Proxy Server [2022 Laos Proxies]',
			code: 'la',
		},
		{
			id: 115,
			name: 'Latvia',
			ips: 106831,
			shortname: 'latvia',
			metaTitle: '🇱🇻 Latvia Proxy Server [2022 Lativia Proxy List]',
			code: 'lv',
		},
		{
			id: 116,
			name: 'Lebanon',
			ips: 106831,
			shortname: 'lebanon',
			metaTitle: '🇱🇧 Lebanon IP Address [2022 Lebanon Proxy]',
			code: 'lb',
		},
		{
			id: 117,
			name: 'Lesotho',
			ips: 106831,
			shortname: 'lesotho',
			metaTitle: '🇱🇸 Lesotho Proxy Server [2022 Lesotho Proxies]',
			code: 'ls',
		},
		{
			id: 118,
			name: 'Liberia',
			ips: 106831,
			shortname: 'liberia',
			metaTitle: '🇱🇷 Liberia Proxy List [2022 Liberia Proxies]',
			code: 'lr',
		},
		{
			id: 119,
			name: 'Libya',
			ips: 106831,
			shortname: 'libya',
			metaTitle: '🇱🇾 Libya Proxy List [2022 Libya Proxy Server]',
			code: 'ly',
		},
		{
			id: 120,
			name: 'Liechtenstein',
			ips: 106831,
			shortname: 'liechtenstein',
			metaTitle: '🇱🇮 Liechtenstein Proxy Server [2022 Liechtenstein Proxies]',
			code: 'li',
		},
		{
			id: 121,
			name: 'Lithuania',
			ips: 106831,
			shortname: 'lithuania',
			metaTitle: '🇱🇹 Proxy Lithuania Server [2022 Lithuania Proxy List]',
			code: 'lt',
		},
		{
			id: 122,
			name: 'Luxembourg',
			ips: 106831,
			shortname: 'luxembourg',
			metaTitle: '🇱🇺 Proxy Luxembourg Server [2022 Luxembourg Proxy]',
			code: 'lu',
		},
		// {
		// 	id: 123,
		// 	name: 'Macau',
		// 	ips: 106831,
		// 	shortname: 'macau',
		// 	code: 'mo',
		// },
		{
			id: 124,
			name: 'North Macedonia',
			ips: 106831,
			shortname: 'north-macedonia',
			metaTitle: '🇲🇰 North Macedonia Proxy Server [2022 Macedonia Proxies]',
			code: 'mk',
		},
		{
			id: 125,
			name: 'Madagascar',
			ips: 106831,
			shortname: 'madagascar',
			metaTitle: '🇲🇬 Madagascar Proxy Server [2022 Madagascar Proxies]',
			code: 'mg',
		},
		{
			id: 126,
			name: 'Malawi',
			ips: 106831,
			shortname: 'malawi',
			metaTitle: '🇲🇼 Malawi Proxy Server [2022 Malawi Proxies]',
			code: 'mw',
		},
		{
			id: 127,
			name: 'Malaysia',
			ips: 106831,
			shortname: 'malaysia',
			metaTitle: '🇲🇾 Malaysia Proxy Server [2022 Malaysia Proxy List]',
			code: 'my',
		},
		{
			id: 128,
			name: 'Maldives',
			ips: 106831,
			shortname: 'maldives',
			metaTitle: '🇲🇻 Proxy Maldives List [2022 Maldives Proxy]',
			code: 'mv',
		},
		{
			id: 129,
			name: 'Mali',
			ips: 106831,
			shortname: 'mali',
			metaTitle: '🇲🇱 Mali Proxy Server [2022 Mali Proxies]',
			code: 'ml',
		},
		{
			id: 130,
			name: 'Malta',
			ips: 106831,
			shortname: 'malta',
			metaTitle: '🇲🇹 Malta Proxy Server [2022 Malta Proxies]',
			code: 'mt',
		},
		{
			id: 131,
			name: 'Marshall Islands',
			ips: 106831,
			shortname: 'marshall-islands',
			metaTitle: '🇲🇭 Marshall Islands Proxy List [2022 Marshall Proxies]',
			code: 'mh',
		},
		{
			id: 132,
			name: 'Mauritania',
			ips: 106831,
			shortname: 'mauritania',
			metaTitle: '🇲🇷 Mauritania Proxy Server [2022 Mauritania Proxies]',
			code: 'mr',
		},
		{
			id: 133,
			name: 'Mauritius',
			ips: 106831,
			shortname: 'mauritius',
			metaTitle: '🇲🇺 Mauritius Proxy Server [2022 Mauritius IP Address]',
			code: 'mu',
		},
		// {
		// 	id: 134,
		// 	name: 'Mayotte',
		// 	ips: 106831,
		// 	shortname: 'mayotte',
		// 	code: 'yt',
		// },
		{
			id: 135,
			name: 'Mexico',
			ips: 106831,
			shortname: 'mexico',
			metaTitle: '🇲🇽 Proxy Mexico Server [2022 Mexico Proxy List]',
			code: 'mx',
		},
		{
			id: 136,
			name: 'Micronesia',
			ips: 106831,
			shortname: 'micronesia',
			metaTitle: '🇫🇲 Micronesia Proxy Server [2022 Micronesia Proxies]',
			code: 'fm',
		},
		{
			id: 137,
			name: 'Moldova',
			ips: 106831,
			shortname: 'moldova',
			metaTitle: '🇲🇩 Moldova Proxy Server [2022 Proxy Moldova List]',
			code: 'md',
		},
		{
			id: 138,
			name: 'Monaco',
			ips: 106831,
			shortname: 'monaco',
			metaTitle: '🇲🇨 Monaco Proxy List [2022 Proxy Monaco List]',
			code: 'mc',
		},
		{
			id: 139,
			name: 'Mongolia',
			ips: 106831,
			shortname: 'mongolia',
			metaTitle: '🇲🇳 Mongolian Proxy Server [2022 Mongolia Proxy]',
			code: 'mn',
		},
		{
			id: 240,
			name: 'Montenegro',
			ips: 106831,
			shortname: 'montenegro',
			metaTitle: '🇲🇪 Montenegro Proxy Server [2022 Montenegro Proxies]',
			code: 'me',
		},
		// {
		// 	id: 140,
		// 	name: 'Montserrat',
		// 	ips: 106831,
		// 	shortname: 'Montserrat',
		// 	code: 'ms',
		// },
		{
			id: 141,
			name: 'Morocco',
			ips: 106831,
			shortname: 'morocco',
			metaTitle: '🇲🇦 Morocco Proxy Server [2022 Moroccan Proxies]',
			code: 'ma',
		},
		{
			id: 142,
			name: 'Mozambique',
			ips: 106831,
			shortname: 'mozambique',
			metaTitle: '🇲🇿 Mozambique Proxy Server [2022 Mozambique Proxies]',
			code: 'mz',
		},
		{
			id: 143,
			name: 'Myanmar',
			ips: 106831,
			shortname: 'myanmar',
			metaTitle: '🇲🇲 Myanmar Proxy Server [2022 Myanmar Proxy List]',
			code: 'mm',
		},
		{
			id: 144,
			name: 'Namibia',
			ips: 106831,
			shortname: 'namibia',
			metaTitle: '🇳🇦 Namibia Proxy Server [2022 Namibia Proxies]',
			code: 'na',
		},
		{
			id: 145,
			name: 'Nauru',
			ips: 106831,
			shortname: 'nauru',
			metaTitle: '🇳🇷 Nauru Proxy Server [2022 Nauru Proxies]',
			code: 'nr',
		},
		{
			id: 146,
			name: 'Nepal',
			ips: 106831,
			shortname: 'nepal',
			metaTitle: '🇳🇵 Nepal Proxy Server [2022 Proxy Nepal]',
			code: 'np',
		},
		{
			id: 147,
			name: 'Netherlands',
			ips: 106831,
			shortname: 'netherlands',
			metaTitle: '🇳🇱 Netherlands Proxy Server [2022 Netherlands Proxy List]',
			code: 'nl',
		},
		// {
		// 	id: 148,
		// 	name: 'Netherlands Antilles',
		// 	ips: 106831,
		// 	shortname: 'netherlands-antilles',
		// 	code: 'an',
		// },
		// {
		// 	id: 149,
		// 	name: 'New Caledonia',
		// 	ips: 106831,
		// 	shortname: 'new-caledonia',
		// 	code: 'nc',
		// },
		{
			id: 150,
			name: 'New Zealand',
			ips: 106831,
			shortname: 'new-zealand',
			metaTitle: '🇳🇿 New Zealand Proxy Server [2022 New Zealand Proxy]',
			code: 'nz',
		},
		{
			id: 151,
			name: 'Nicaragua',
			ips: 106831,
			shortname: 'nicaragua',
			metaTitle: '🇳🇮 Nicaragua Proxy Server [2022 Proxy Nicaragua List]',
			code: 'ni',
		},
		{
			id: 152,
			name: 'Niger',
			ips: 106831,
			shortname: 'niger',
			metaTitle: '🇳🇪 Niger Proxy Server [2022 Niger Proxy List]',
			code: 'ne',
		},
		{
			id: 153,
			name: 'Nigeria',
			ips: 106831,
			shortname: 'nigeria',
			metaTitle: '🇳🇬 Nigeria IP Proxy [2022 Proxy Nigeria]',
			code: 'ng',
		},
		// {
		// 	id: 154,
		// 	name: 'Niue',
		// 	ips: 106831,
		// 	shortname: 'niue',
		// 	code: 'nu',
		// },
		{
			id: 155,
			name: 'North Korea',
			ips: 106831,
			shortname: 'north-korea',
			metaTitle: '🇰🇵 North Korea Proxy Server [2022 North Korea Proxies]',
			code: 'kp',
		},
		// {
		// 	id: 156,
		// 	name: 'Northern Mariana Islands',
		// 	ips: 106831,
		// 	shortname: 'northern-mariana-islands',
		// 	code: 'mp',
		// },
		{
			id: 157,
			name: 'Norway',
			ips: 106831,
			shortname: 'norway',
			metaTitle: '🇳🇴 Norway Proxy Server [2022 Norwegian Proxy List]',
			code: 'no',
		},
		{
			id: 158,
			name: 'Oman',
			ips: 106831,
			shortname: 'oman',
			metaTitle: '🇴🇲 Oman Proxy Server [2022 Oman Proxy]',
			code: 'om',
		},
		{
			id: 159,
			name: 'Pakistan',
			ips: 106831,
			shortname: 'pakistan',
			metaTitle: '🇵🇰 Pakistan Proxy Server [2022 List]',
			code: 'pk',
		},
		{
			id: 160,
			name: 'Palau',
			ips: 106831,
			shortname: 'palau',
			metaTitle: '🇵🇼 Palau Proxy Server [2022 Palau Proxies]',
			code: 'pw',
		},
		{
			id: 161,
			name: 'Palestine',
			ips: 106831,
			shortname: 'palestine',
			metaTitle: '🇵🇸 Palestine Proxy Server [2022 Palestinian Proxy List]',
			code: 'ps',
		},
		{
			id: 162,
			name: 'Panama',
			ips: 106831,
			shortname: 'panama',
			metaTitle: '🇵🇦 Proxy Panama Server [2022 Panama IP List]',
			code: 'pa',
		},
		{
			id: 163,
			name: 'Papua New Guinea',
			ips: 106831,
			shortname: 'papua-new-guinea',
			metaTitle: '🇬🇳 Papua New Guinea Proxy Server [2022 Proxy List]',
			code: 'pg',
		},
		{
			id: 164,
			name: 'Paraguay',
			ips: 106831,
			shortname: 'paraguay',
			metaTitle: '🇵🇾 Proxy Paraguay Server [2022 Paraguay Proxy List]',
			code: 'py',
		},
		{
			id: 165,
			name: 'Peru',
			ips: 106831,
			shortname: 'peru',
			metaTitle: '🇵🇪 Proxy Peru Server [2022 Peru Proxy List]',
			code: 'pe',
		},
		{
			id: 166,
			name: 'Philippines',
			ips: 106831,
			shortname: 'philippines',
			metaTitle: '🇵🇭 Phillippines Proxy Server [2022 Philippines Proxy List]',
			code: 'ph',
		},
		// {
		// 	id: 167,
		// 	name: 'Pitcairn',
		// 	ips: 106831,
		// 	shortname: 'pitcairn',
		// 	code: 'pn',
		// },
		{
			id: 168,
			name: 'Poland',
			ips: 106831,
			shortname: 'poland',
			metaTitle: '🇵🇱 Polish Proxy Server [2022 Poland Proxy]',
			code: 'pl',
		},
		{
			id: 169,
			name: 'Portugal',
			ips: 106831,
			shortname: 'portugal',
			metaTitle: '🇵🇹 Proxy Portugal Server [2022 Proxy Portugal List]',
			code: 'pt',
		},
		{
			id: 170,
			name: 'Puerto Rico',
			ips: 106831,
			shortname: 'puerto-rico',
			metaTitle: '🇵🇷 Puerto Rico Proxy Server [2022 Proxy Puerto Rico]',
			code: 'pr',
		},
		{
			id: 171,
			name: 'Qatar',
			ips: 106831,
			shortname: 'qatar',
			metaTitle: '🇶🇦 Qatar Proxy Server [2022 Qatar Proxy List]',
			code: 'qa',
		},
		{
			id: 172,
			name: 'Republic of the Congo',
			ips: 106831,
			shortname: 'republic-of-the-congo',
			metaTitle: '🇨🇬 Republic of the Congo Proxy Server [2022 Congo Proxies]',
			code: 'cg',
		},
		// {
		// 	id: 173,
		// 	name: 'Reunion',
		// 	ips: 106831,
		// 	shortname: 'reunion',
		// 	code: 're',
		// },
		{
			id: 174,
			name: 'Romania',
			ips: 106831,
			shortname: 'romania',
			metaTitle: '🇷🇴 Romania Proxy Server [2022 Romanian Proxy List]',
			code: 'ro',
		},
		{
			id: 175,
			name: 'Russia',
			ips: 106831,
			shortname: 'russia',
			metaTitle: '🇷🇺 Russian Proxy Server [2022 Russian Proxy List]',
			code: 'ru',
		},
		{
			id: 176,
			name: 'Rwanda',
			ips: 106831,
			shortname: 'rwanda',
			metaTitle: '🇷🇼 Rwanda Proxy Server [2022 Rwanda Proxies]',
			code: 'rw',
		},
		// {
		// 	id: 177,
		// 	name: 'Saint Barthelemy',
		// 	ips: 106831,
		// 	shortname: 'saint-barthelemy',
		// 	code: 'bl',
		// },
		// {
		// 	id: 178,
		// 	name: 'Saint Helena',
		// 	ips: 106831,
		// 	shortname: 'saint-helena',
		// 	code: 'sh',
		// },
		{
			id: 179,
			name: 'Saint Kitts and Nevis',
			ips: 106831,
			shortname: 'saint-kitts-and-nevis',
			metaTitle: '🇰🇳 Saint Kitts and Nevis Proxy Server [2022 Proxies]',
			code: 'kn',
		},
		{
			id: 180,
			name: 'Saint Lucia',
			ips: 106831,
			shortname: 'saint-lucia',
			metaTitle: '🇱🇨 Saint Lucia Proxy Server [2022 Saint Lucia Proxy]',
			code: 'lc',
		},
		// {
		// 	id: 181,
		// 	name: 'Saint Martin',
		// 	ips: 106831,
		// 	shortname: 'saint-martin',
		// 	code: 'mf',
		// },
		// {
		// 	id: 182,
		// 	name: 'Saint Pierre and Miquelon',
		// 	ips: 106831,
		// 	shortname: 'Saint-pierre-and-miquelon',
		// 	code: 'pm',
		// },
		{
			id: 183,
			name: 'Saint Vincent and the Grenadines',
			ips: 106831,
			shortname: 'saint-vincent-and-the-grenadines',
			metaTitle: '🇻🇨 Saint Vincent and the Grenadines Proxy Server',
			code: 'vc',
		},
		{
			id: 184,
			name: 'Samoa',
			ips: 106831,
			shortname: 'samoa',
			metaTitle: '🇸🇲 Samoa Proxy Server [2022 Samoa Proxies]',
			code: 'ws',
		},
		{
			id: 185,
			name: 'San Marino',
			ips: 106831,
			shortname: 'san-marino',
			metaTitle: '🇸🇹 San Marino Proxy Server [2022 Proxy San Marino]',
			code: 'sm',
		},
		{
			id: 186,
			name: 'Sao Tome and Principe',
			ips: 106831,
			shortname: 'sao-tome-and-principe',
			metaTitle: '🇸🇦 Sao Tome and Principe Proxy Server [2022 Proxy List]',
			code: 'st',
		},
		{
			id: 187,
			name: 'Saudi Arabia',
			ips: 106831,
			shortname: 'saudi-arabia',
			metaTitle: '🇸🇳 Saudi Arabia Proxy Server [2022 KSA Proxy List]',
			code: 'sa',
		},
		{
			id: 188,
			name: 'Senegal',
			ips: 106831,
			shortname: 'senegal',
			metaTitle: '🇷🇸 Senegal Proxy Server [2022 Senegal Proxy List]',
			code: 'sn',
		},
		{
			id: 189,
			name: 'Serbia',
			ips: 106831,
			shortname: 'serbia',
			metaTitle: '🇸🇨 Serbia Proxy Server [2022 Serbian Proxy List]',
			code: 'rs',
		},
		{
			id: 190,
			name: 'Seychelles',
			ips: 106831,
			shortname: 'seychelles',
			metaTitle: '🇸🇱 Seychelles Proxy Server [2022 Seychelles Proxy List]',
			code: 'sc',
		},
		{
			id: 191,
			name: 'Sierra Leone',
			ips: 106831,
			shortname: 'sierra-leone',
			metaTitle: '🇸🇬 Sierra Leone Proxy Server [2022 Proxy List]',
			code: 'sl',
		},
		{
			id: 192,
			name: 'Singapore',
			ips: 106831,
			shortname: 'singapore',
			metaTitle: '🇸🇰 Singapore Proxy Server [2022 Singapore Proxies]',
			code: 'sg',
		},
		// {
		// 	id: 193,
		// 	name: 'Sint Maarten',
		// 	ips: 106831,
		// 	shortname: 'sint-maarten',
		// 	code: 'sx',
		// },
		{
			id: 194,
			name: 'Slovakia',
			ips: 106831,
			shortname: 'slovakia',
			metaTitle: '🇸🇮 Slovakia Proxy Server [2022 Slovakia Web Proxy]',
			code: 'sk',
		},
		{
			id: 195,
			name: 'Slovenia',
			ips: 106831,
			shortname: 'slovenia',
			metaTitle: '🇸🇮 Slovenia Proxy Server [2022 Slovenia Proxy]',
			code: 'si',
		},
		{
			id: 196,
			name: 'Solomon Islands',
			ips: 106831,
			shortname: 'solomon-islands',
			metaTitle: '🇸🇧 Solomon Islands Proxies [2022]',
			code: 'sb',
		},
		{
			id: 197,
			name: 'Somalia',
			ips: 106831,
			shortname: 'somalia',
			metaTitle: '🇸🇴 Somalia Proxy Server [2022 Somalia Proxy List]',
			code: 'so',
		},
		{
			id: 198,
			name: 'South Africa',
			ips: 106831,
			shortname: 'south-africa',
			metaTitle: '🇿🇦 South Africa Proxy Server [2022 SA Proxy List]',
			code: 'za',
		},
		{
			id: 199,
			name: 'South Korea',
			ips: 106831,
			shortname: 'south-korea',
			metaTitle: '🇰🇷 Korean Proxy Server [2022 Korea Proxy List]',
			code: 'kr',
		},
		// {
		// 	id: 200,
		// 	name: 'South Sudan',
		// 	ips: 106831,
		// 	shortname: 'south-sudan',
		// 	code: 'ss',
		// },
		{
			id: 201,
			name: 'Spain',
			ips: 106831,
			shortname: 'spain',
			metaTitle: '🇪🇸 Spain Proxy Server [2022 Spanish Proxy]',
			code: 'es',
		},
		{
			id: 202,
			name: 'Sri Lanka',
			ips: 106831,
			shortname: 'sri-lanka',
			metaTitle: '🇱🇰 Sri Lanka Proxy Server [2022 Sri Lanka Proxy]',
			code: 'lk',
		},
		{
			id: 203,
			name: 'Sudan',
			ips: 106831,
			shortname: 'sudan',
			metaTitle: '🇸🇩 Sudan Proxy Server [2022 Sudan Proxy List]',
			code: 'sd',
		},
		{
			id: 204,
			name: 'Suriname',
			ips: 106831,
			shortname: 'suriname',
			metaTitle: '🇸🇷 Suriname Proxy Server [2022 Suriname Proxy List]',
			code: 'sr',
		},
		// {
		// 	id: 205,
		// 	name: 'Svalbard and Jan Mayen',
		// 	ips: 106831,
		// 	shortname: 'svalbard-and-jan-mayen',
		// 	code: 'sj',
		// },
		{
			id: 206,
			name: 'Swaziland',
			ips: 106831,
			shortname: 'swaziland',
			metaTitle: '🇸🇿 Swaziland Proxy Server [2022 Swaziland Proxy List]',
			code: 'sz',
		},
		{
			id: 207,
			name: 'Sweden',
			ips: 106831,
			shortname: 'sweden',
			metaTitle: '🇸🇪 Sweden Proxy Server [2022 Swedish Proxy]',
			code: 'se',
		},
		{
			id: 208,
			name: 'Switzerland',
			ips: 106831,
			shortname: 'switzerland',
			metaTitle: '🇨🇭 Switzerland Proxy Server [2022 Switzerland Proxy Site]',
			code: 'ch',
		},
		{
			id: 209,
			name: 'Syria',
			ips: 106831,
			shortname: 'syria',
			metaTitle: '🇸🇾 Syria Proxy Server [2022 Syrian Proxy]',
			code: 'sy',
		},
		{
			id: 210,
			name: 'Taiwan',
			ips: 106831,
			shortname: 'taiwan',
			metaTitle: '🇹🇼 Taiwan Proxy Server [2022 Taiwan Web Proxy]',
			code: 'tw',
		},
		{
			id: 211,
			name: 'Tajikistan',
			ips: 106831,
			shortname: 'tajikistan',
			metaTitle: '🇹🇯 Tajikistan Proxy Server [2022 Tajikistan Proxy List]',
			code: 'tj',
		},
		{
			id: 212,
			name: 'Tanzania',
			ips: 106831,
			shortname: 'tanzania',
			metaTitle: '🇹🇿 Tanzania Proxy Server [2022 Tanzania Proxy]',
			code: 'tz',
		},
		{
			id: 213,
			name: 'Thailand',
			ips: 106831,
			shortname: 'thailand',
			metaTitle: '🇹🇭 Thailand Proxy Server [2022 Proxy Thailand]',
			code: 'th',
		},
		{
			id: 214,
			name: 'Togo',
			ips: 106831,
			shortname: 'togo',
			metaTitle: '🇹🇬 Togo Proxy Server [2022 Togo Proxy List]',
			code: 'tg',
		},
		{
			id: 215,
			name: 'Tokelau',
			ips: 106831,
			shortname: 'tokelau',
			metaTitle: '🇹🇰 Tokelau Proxy Server [2022 Tokelau Proxies]',
			code: 'tk',
		},
		{
			id: 216,
			name: 'Tonga',
			ips: 106831,
			shortname: 'tonga',
			metaTitle: '🇹🇴 Tonga Proxy Server [2022 Tonga Proxy List]',
			code: 'to',
		},
		{
			id: 217,
			name: 'Trinidad and Tobago',
			ips: 106831,
			shortname: 'trinidad-and-tobago',
			metaTitle: '🇹🇹 Trinidad and Tobago Proxy List [2022 Proxy List]',
			code: 'tt',
		},
		{
			id: 218,
			name: 'Tunisia',
			ips: 106831,
			shortname: 'tunisia',
			metaTitle: '🇹🇳 Tunisia Proxy Server [2022 Tunisia Proxies]',
			code: 'tn',
		},
		{
			id: 219,
			name: 'Turkey',
			ips: 106831,
			shortname: 'turkey',
			metaTitle: '🇹🇷 Turkey Proxy Server [2022 Turkish Proxy]',
			code: 'tr',
		},
		{
			id: 220,
			name: 'Turkmenistan',
			ips: 106831,
			shortname: 'turkmenistan',
			metaTitle: '🇹🇲 Turkmenistan Proxy Server [2022 Turkmenistan Proxy]',
			code: 'tm',
		},
		{
			id: 221,
			name: 'Turks and Caicos Islands',
			ips: 106831,
			shortname: 'turks-and-caicos-islands',
			metaTitle: '🇹🇨 Turks and Caicos Islands Proxy Server [2022 Proxy List]',
			code: 'tc',
		},
		{
			id: 222,
			name: 'Tuvalu',
			ips: 106831,
			shortname: 'tuvalu',
			metaTitle: '🇹🇻 Tuvalu Proxy Server [2022 Tuvalu Proxy List]',
			code: 'tv',
		},
		// {
		// 	id: 223,
		// 	name: 'U.S. Virgin Islands',
		// 	ips: 106831,
		// 	shortname: 'us-virgin-islands',
		// 	code: 'vi',
		// },
		{
			id: 224,
			name: 'Uganda',
			ips: 106831,
			shortname: 'uganda',
			metaTitle: '🇺🇬 Uganda Proxy Server [2022 Uganda Proxies]',
			code: 'ug',
		},
		{
			id: 225,
			name: 'Ukraine',
			ips: 106831,
			shortname: 'ukraine',
			metaTitle: '🇺🇦 Ukraine Proxy Server [2022 Ukrainian Proxy]',
			code: 'ua',
		},
		{
			id: 226,
			name: 'United Arab Emirates',
			ips: 106831,
			shortname: 'united-arab-emirates',
			metaTitle: '🇦🇪 United Arab Emirated Proxies [2022 UAE Proxies]',
			code: 'ae',
		},
		{
			id: 227,
			name: 'United Kingdom',
			ips: 106831,
			shortname: 'united-kingdom',
			metaTitle: '🇬🇧 UK Proxies Server [2022 United Kingdom Proxy]',
			code: 'gb',
		},
		{
			id: 228,
			name: 'United States',
			ips: 106831,
			shortname: 'united-states',
			metaTitle: '🇺🇸 US Proxies Server [2022 United States Proxy]',
			code: 'us',
		},
		{
			id: 229,
			name: 'Uruguay',
			ips: 106831,
			shortname: 'uruguay',
			metaTitle: '🇺🇾 Proxy Uruguay Server [2022 Proxy Uruguay]',
			code: 'uy',
		},
		{
			id: 230,
			name: 'Uzbekistan',
			ips: 106831,
			shortname: 'uzbekistan',
			metaTitle: '🇺🇿 Uzbekistan Proxy Server [2022 Proxy Uzbekistan]',
			code: 'uz',
		},
		{
			id: 231,
			name: 'Vanuatu',
			ips: 106831,
			shortname: 'vanuatu',
			metaTitle: '🇻🇺 Vanuatu Proxy Server [2022 Vanuatu Proxy List]',
			code: 'vu',
		},
		// {
		// 	id: 232,
		// 	name: 'Vatican',
		// 	ips: 106831,
		// 	shortname: 'vatican',
		// 	code: 'va',
		// },
		{
			id: 233,
			name: 'Venezuela',
			ips: 106831,
			shortname: 'venezuela',
			metaTitle: '🇻🇪 Venezuela Proxy Server [2022 Venezuela Proxy List]',
			code: 've',
		},
		{
			id: 234,
			name: 'Vietnam',
			ips: 106831,
			shortname: 'vietnam',
			metaTitle: '🇻🇳 Vietnam Proxy Server [2022 Proxy Vietnam]',
			code: 'vn',
		},
		// {
		// 	id: 235,
		// 	name: 'Wallis and Futuna',
		// 	ips: 106831,
		// 	shortname: 'wallis-and-futuna',
		// 	code: 'wf',
		// },
		// {
		// 	id: 236,
		// 	name: 'Western Sahara',
		// 	ips: 106831,
		// 	shortname: 'western-sahara',
		// 	code: 'eh',
		// },
		{
			id: 237,
			name: 'Yemen',
			ips: 106831,
			shortname: 'yemen',
			metaTitle: '🇾🇪 Yemen Proxy Server [2022 Yemen Proxy List]',
			code: 'ye',
		},
		{
			id: 238,
			name: 'Zambia',
			ips: 106831,
			shortname: 'zambia',
			metaTitle: '🇿🇲 Zambia Proxy Server [2022 Zambia Proxy List]',
			code: 'zm',
		},
		{
			id: 239,
			name: 'Zimbabwe',
			ips: 106831,
			shortname: 'zimbabwe',
			metaTitle: '🇿🇼 Zimbabwe Proxy Server [2022 Zimbabwe Proxies]',
			code: 'zw',
		},
	],
};
